### ISSUE TITLE
Uninstall "execSync" Dependency

### ISSUE THREAD

**Issue by joeydong** [sunrise/quick-coverage#2]
The "execSync" package does not work with Node 0.12.x. I would upgrade Node requirement to 0.12.x in the `package.json` and remove "execSync" dependency.

**Comment by mariecl** [comment]
Instead of upgrading the Node requirement, I used [`sync-exec`](https://github.com/gvarsanyi/sync-exec) which very similar to `execSync` except that it preserves compatibility with Node versions older and newer than 0.12.x:

![screen shot 2015-05-12 at 5 12 39 pm](https://cloud.githubusercontent.com/assets/9665980/7598670/220bb028-f8ca-11e4-8d51-f48652a0456d.png)

**Comment by joeydong** [comment]
The [sync-exec license](https://github.com/gvarsanyi/sync-exec/blob/master/LICENSE) is not compatible with our MIT License so you need to find another solution.

**Comment by mariecl** [comment]
Thanks for pointing it out. I think the solution for that problem would be to check for the node version currently running, and if it's older than 0.12., use execSync, otherwise, use native options.

However, while researching the question, I found out that Istanbul is licensed under the BSD 3 clauses license, not MIT. Since this project is not modifying Istanbul, it seems like Istanbul keeps its own license inside our project, and the final project can still be distributed with the MIT license as long as we mention that Istanbul is licensed under the BSD license, to comply with the additional restriction of the BSD license.

Can you infirm/confirm @joeydong ?

**Comment by mariecl** [comment]
Closing as the issue with `execSync` was resolved.
Discussion regarding licences will happen in #9.
